openapi: 3.0.1
info:
  version: 1.0.0
  title: test API
  description: Swagger open api 3.0 연습
servers:
  - url: http://localhost:{port}/{basePath}
    description: Local Server
    variables:
      port:
        default: 3000
      basePath:
        default: v1
paths: # object
  $ref: './swagger/paths/index.yaml'
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Board:
      $ref: './swagger/definitions/Board.yaml'
    Code:
      $ref: './swagger/definitions/Code.yaml'
    File:
      $ref: './swagger/definitions/File.yaml'
    Font:
      $ref: './swagger/definitions/Font.yaml'
    User:
      $ref: './swagger/definitions/User.yaml'